### ISSUE TITLE
Overview History, Firebase 

### ISSUE THREAD

**Issue by odong95** [jtexp/NutriScope#19]
When logged in as a user (lately), then log out, then sign in to another account (john): Lately's nutrition history gets loaded up instead of John's.

Firebase update, not adding all food nutrients and overriding values instead of adding to them.

**Comment by jtexp** [comment]
there's a logger for firebase I put in to track user login state

Nutriscope/app/src/main/java/edu/utdallas/csdesign/spring17/nutriscope/util/FirebaseLogger.java

I think we need to create a singleton for the User state and then have every other firebase class depend on it as an Observer so that we can propagate user changes.

Also I think we could add some rules to our firebase so that a user can't read other user's info. That way if something like this happens it will fail in an obvious way.

**Comment by jtexp** [comment]
0cc59ad
